window.symbols = {
"stage": {
   version: "0.1",
   baseState: "Base State",
   initialState: "Base State",
   parameters: {

   },
   content: {
      dom: [
        {
            id:'background',
            type:'image',
            rect:[0,0,940,200],
            fill:['rgba(0,0,0,0)','../img/background.png'],
        },
        {
            id:'Cow',
            type:'image',
            rect:[0,0,94,114],
            fill:['rgba(0,0,0,0)','../img/cow.png'],
        },
        {
            id:'Giraffee',
            type:'image',
            rect:[0,0,73,133],
            fill:['rgba(0,0,0,0)','../img/giraffe.png'],
        },
        {
            id:'Hippo',
            type:'image',
            rect:[0,0,101,106],
            fill:['rgba(0,0,0,0)','../img/hippo.png'],
        },
        {
            id:'pig',
            type:'image',
            rect:[0,0,104,109],
            fill:['rgba(0,0,0,0)','../img/pig.png'],
        },
        {
            id:'owl',
            type:'image',
            rect:[0,0,111,107],
            fill:['rgba(0,0,0,0)','../img/owl.png'],
        },
        {
            id:'zebra',
            type:'image',
            rect:[0,0,86,104],
            fill:['rgba(0,0,0,0)','../img/zebra.png'],
        },
        {
            id:'goat',
            type:'image',
            rect:[0,0,106,133],
            fill:['rgba(0,0,0,0)','../img/goat.png'],
        },
      ],
      symbolInstances: [
      ],
   },
   states: {
      "Base State": {
         "#pig": [
            ["transform", "translateX", '-482px'],
            ["transform", "translateY", '96px'],
            ["transform", "rotateZ", '-5deg']
         ],
         "#stage": [
            ["color", "background-color", 'rgba(255,255,255,1)'],
            ["style", "overflow", 'hidden'],
            ["style", "height", '200px'],
            ["style", "width", '854px']
         ],
         "#owl": [
            ["transform", "rotateZ", '-5deg'],
            ["transform", "translateX", '-228px'],
            ["transform", "translateY", '92px'],
            ["style", "width", '106px']
         ],
         "#Cow": [
            ["transform", "rotateZ", '-5deg'],
            ["transform", "translateX", '-817px'],
            ["transform", "translateY", '84px'],
            ["style", "width", '92px']
         ],
         "#zebra": [
            ["transform", "translateX", '-84px'],
            ["transform", "translateY", '95px'],
            ["transform", "rotateZ", '-5deg']
         ],
         "#goat": [
            ["transform", "rotateZ", '-5deg'],
            ["transform", "translateX", '-345px'],
            ["transform", "translateY", '70px'],
            ["style", "width", '98px']
         ],
         "#Hippo": [
            ["transform", "translateX", '-606px'],
            ["transform", "rotateZ", '-5deg'],
            ["style", "height", '107px'],
            ["transform", "translateY", '88px'],
            ["style", "width", '96px']
         ],
         "#Giraffee": [
            ["transform", "rotateZ", '-5deg'],
            ["transform", "translateX", '-693px'],
            ["transform", "translateY", '73px'],
            ["style", "width", '68px']
         ]
      }
   },
   actions: {

   },
   bindings: [

   ],
   timelines: {
      "Default Timeline": {
         fromState: "Base State",
         toState: "",
         duration: 15075.808827184,
         timeline: [
            { id: "eid68", tween: [ "style", "#Hippo", "height", '107px', { valueTemplate: undefined, fromValue: '107px'}], position: 0, duration: 0, easing: "linear" },
            { id: "eid32", tween: [ "style", "#Cow", "width", '92px', { valueTemplate: undefined, fromValue: '92px'}], position: 0, duration: 0, easing: "linear" },
            { id: "eid606", tween: [ "style", "#stage", "height", '200px', { valueTemplate: undefined, fromValue: '200px'}], position: 15075, duration: 0, easing: "linear" },
            { id: "eid107", tween: [ "transform", "#Cow", "translateX", '-582px', { valueTemplate: undefined, fromValue: '-817px'}], position: 0, duration: 3000, easing: "linear" },
            { id: "eid123", tween: [ "transform", "#Cow", "translateX", '-511px', { valueTemplate: undefined, fromValue: '-582px'}], position: 3000, duration: 1000, easing: "linear" },
            { id: "eid137", tween: [ "transform", "#Cow", "translateX", '-436px', { valueTemplate: undefined, fromValue: '-511px'}], position: 4000, duration: 1000, easing: "linear" },
            { id: "eid151", tween: [ "transform", "#Cow", "translateX", '-167px', { valueTemplate: undefined, fromValue: '-436px'}], position: 5000, duration: 5000, easing: "linear" },
            { id: "eid160", tween: [ "transform", "#Cow", "translateX", '2px', { valueTemplate: undefined, fromValue: '-167px'}], position: 10000, duration: 5000, easing: "linear" },
            { id: "eid101", tween: [ "transform", "#pig", "translateX", '-247px', { valueTemplate: undefined, fromValue: '-482px'}], position: 0, duration: 3000, easing: "linear" },
            { id: "eid117", tween: [ "transform", "#pig", "translateX", '-176px', { valueTemplate: undefined, fromValue: '-247px'}], position: 3000, duration: 1000, easing: "linear" },
            { id: "eid131", tween: [ "transform", "#pig", "translateX", '-101px', { valueTemplate: undefined, fromValue: '-176px'}], position: 4000, duration: 1000, easing: "linear" },
            { id: "eid145", tween: [ "transform", "#pig", "translateX", '168px', { valueTemplate: undefined, fromValue: '-101px'}], position: 5000, duration: 5000, easing: "linear" },
            { id: "eid157", tween: [ "transform", "#pig", "translateX", '337px', { valueTemplate: undefined, fromValue: '168px'}], position: 10000, duration: 5000, easing: "linear" },
            { id: "eid102", tween: [ "transform", "#pig", "translateY", '92px', { valueTemplate: undefined, fromValue: '96px'}], position: 0, duration: 3000, easing: "linear" },
            { id: "eid118", tween: [ "transform", "#pig", "translateY", '93px', { valueTemplate: undefined, fromValue: '92px'}], position: 3000, duration: 1000, easing: "linear" },
            { id: "eid132", tween: [ "transform", "#pig", "translateY", '94px', { valueTemplate: undefined, fromValue: '93px'}], position: 4000, duration: 1000, easing: "linear" },
            { id: "eid146", tween: [ "transform", "#pig", "translateY", '91px', { valueTemplate: undefined, fromValue: '94px'}], position: 5000, duration: 5000, easing: "linear" },
            { id: "eid97", tween: [ "transform", "#goat", "translateX", '-325.41666666667px', { valueTemplate: undefined, fromValue: '-345px'}], position: 0, duration: 250, easing: "linear" },
            { id: "eid168", tween: [ "transform", "#goat", "translateX", '-286.25px', { valueTemplate: undefined, fromValue: '-325.41666666667px'}], position: 250, duration: 500, easing: "linear" },
            { id: "eid173", tween: [ "transform", "#goat", "translateX", '-110px', { valueTemplate: undefined, fromValue: '-286.25px'}], position: 750, duration: 2250, easing: "linear" },
            { id: "eid113", tween: [ "transform", "#goat", "translateX", '-39px', { valueTemplate: undefined, fromValue: '-110px'}], position: 3000, duration: 1000, easing: "linear" },
            { id: "eid127", tween: [ "transform", "#goat", "translateX", '36px', { valueTemplate: undefined, fromValue: '-39px'}], position: 4000, duration: 1000, easing: "linear" },
            { id: "eid141", tween: [ "transform", "#goat", "translateX", '305px', { valueTemplate: undefined, fromValue: '36px'}], position: 5000, duration: 5000, easing: "linear" },
            { id: "eid155", tween: [ "transform", "#goat", "translateX", '474px', { valueTemplate: undefined, fromValue: '305px'}], position: 10000, duration: 5000, easing: "linear" },
            { id: "eid106", tween: [ "transform", "#owl", "translateY", '88px', { valueTemplate: undefined, fromValue: '92px'}], position: 0, duration: 3000, easing: "linear" },
            { id: "eid122", tween: [ "transform", "#owl", "translateY", '89px', { valueTemplate: undefined, fromValue: '88px'}], position: 3000, duration: 1000, easing: "linear" },
            { id: "eid136", tween: [ "transform", "#owl", "translateY", '90px', { valueTemplate: undefined, fromValue: '89px'}], position: 4000, duration: 1000, easing: "linear" },
            { id: "eid150", tween: [ "transform", "#owl", "translateY", '87px', { valueTemplate: undefined, fromValue: '90px'}], position: 5000, duration: 5000, easing: "linear" },
            { id: "eid41", tween: [ "style", "#owl", "width", '106px', { valueTemplate: undefined, fromValue: '106px'}], position: 0, duration: 0, easing: "linear" },
            { id: "eid112", tween: [ "style", "#owl", "width", '106px', { valueTemplate: undefined, fromValue: '106px'}], position: 3000, duration: 0, easing: "linear" },
            { id: "eid405", tween: [ "transform", "#goat", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 0, duration: 508, easing: "linear" },
            { id: "eid406", tween: [ "transform", "#goat", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 508, duration: 508, easing: "linear" },
            { id: "eid407", tween: [ "transform", "#goat", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 1016, duration: 508, easing: "linear" },
            { id: "eid408", tween: [ "transform", "#goat", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 1524, duration: 508, easing: "linear" },
            { id: "eid409", tween: [ "transform", "#goat", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 2032, duration: 508, easing: "linear" },
            { id: "eid410", tween: [ "transform", "#goat", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 2540, duration: 508, easing: "linear" },
            { id: "eid411", tween: [ "transform", "#goat", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 3048, duration: 508, easing: "linear" },
            { id: "eid412", tween: [ "transform", "#goat", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 3557, duration: 508, easing: "linear" },
            { id: "eid413", tween: [ "transform", "#goat", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 4065, duration: 508, easing: "linear" },
            { id: "eid414", tween: [ "transform", "#goat", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 4573, duration: 508, easing: "linear" },
            { id: "eid415", tween: [ "transform", "#goat", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 5081, duration: 508, easing: "linear" },
            { id: "eid416", tween: [ "transform", "#goat", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 5589, duration: 508, easing: "linear" },
            { id: "eid417", tween: [ "transform", "#goat", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 6097, duration: 508, easing: "linear" },
            { id: "eid418", tween: [ "transform", "#goat", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 6605, duration: 508, easing: "linear" },
            { id: "eid419", tween: [ "transform", "#goat", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 7114, duration: 508, easing: "linear" },
            { id: "eid420", tween: [ "transform", "#goat", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 7622, duration: 508, easing: "linear" },
            { id: "eid421", tween: [ "transform", "#goat", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 8130, duration: 508, easing: "linear" },
            { id: "eid422", tween: [ "transform", "#goat", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 8638, duration: 508, easing: "linear" },
            { id: "eid423", tween: [ "transform", "#goat", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 9146, duration: 508, easing: "linear" },
            { id: "eid424", tween: [ "transform", "#goat", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 9654, duration: 508, easing: "linear" },
            { id: "eid425", tween: [ "transform", "#goat", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 10162, duration: 508, easing: "linear" },
            { id: "eid426", tween: [ "transform", "#goat", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 10671, duration: 508, easing: "linear" },
            { id: "eid427", tween: [ "transform", "#goat", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 11179, duration: 508, easing: "linear" },
            { id: "eid428", tween: [ "transform", "#goat", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 11687, duration: 508, easing: "linear" },
            { id: "eid429", tween: [ "transform", "#goat", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 12195, duration: 508, easing: "linear" },
            { id: "eid430", tween: [ "transform", "#goat", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 12703, duration: 508, easing: "linear" },
            { id: "eid431", tween: [ "transform", "#goat", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 13211, duration: 508, easing: "linear" },
            { id: "eid432", tween: [ "transform", "#goat", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 13719, duration: 508, easing: "linear" },
            { id: "eid433", tween: [ "transform", "#goat", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 14228, duration: 508, easing: "linear" },
            { id: "eid434", tween: [ "transform", "#goat", "rotateZ", '0deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 14736, duration: 263, easing: "linear" },
            { id: "eid109", tween: [ "transform", "#Hippo", "translateX", '-371px', { valueTemplate: undefined, fromValue: '-606px'}], position: 0, duration: 3000, easing: "linear" },
            { id: "eid125", tween: [ "transform", "#Hippo", "translateX", '-300px', { valueTemplate: undefined, fromValue: '-371px'}], position: 3000, duration: 1000, easing: "linear" },
            { id: "eid139", tween: [ "transform", "#Hippo", "translateX", '-225px', { valueTemplate: undefined, fromValue: '-300px'}], position: 4000, duration: 1000, easing: "linear" },
            { id: "eid153", tween: [ "transform", "#Hippo", "translateX", '44px', { valueTemplate: undefined, fromValue: '-225px'}], position: 5000, duration: 5000, easing: "linear" },
            { id: "eid161", tween: [ "transform", "#Hippo", "translateX", '213px', { valueTemplate: undefined, fromValue: '44px'}], position: 10000, duration: 5000, easing: "linear" },
            { id: "eid555", tween: [ "transform", "#Cow", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 0, duration: 474, easing: "linear" },
            { id: "eid556", tween: [ "transform", "#Cow", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 474, duration: 474, easing: "linear" },
            { id: "eid557", tween: [ "transform", "#Cow", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 949, duration: 474, easing: "linear" },
            { id: "eid558", tween: [ "transform", "#Cow", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 1424, duration: 474, easing: "linear" },
            { id: "eid559", tween: [ "transform", "#Cow", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 1898, duration: 474, easing: "linear" },
            { id: "eid560", tween: [ "transform", "#Cow", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 2373, duration: 474, easing: "linear" },
            { id: "eid561", tween: [ "transform", "#Cow", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 2848, duration: 474, easing: "linear" },
            { id: "eid562", tween: [ "transform", "#Cow", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 3322, duration: 474, easing: "linear" },
            { id: "eid563", tween: [ "transform", "#Cow", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 3797, duration: 474, easing: "linear" },
            { id: "eid564", tween: [ "transform", "#Cow", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 4272, duration: 474, easing: "linear" },
            { id: "eid565", tween: [ "transform", "#Cow", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 4746, duration: 474, easing: "linear" },
            { id: "eid566", tween: [ "transform", "#Cow", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 5221, duration: 474, easing: "linear" },
            { id: "eid567", tween: [ "transform", "#Cow", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 5696, duration: 474, easing: "linear" },
            { id: "eid568", tween: [ "transform", "#Cow", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 6170, duration: 474, easing: "linear" },
            { id: "eid569", tween: [ "transform", "#Cow", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 6645, duration: 474, easing: "linear" },
            { id: "eid570", tween: [ "transform", "#Cow", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 7120, duration: 474, easing: "linear" },
            { id: "eid571", tween: [ "transform", "#Cow", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 7594, duration: 474, easing: "linear" },
            { id: "eid572", tween: [ "transform", "#Cow", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 8069, duration: 474, easing: "linear" },
            { id: "eid573", tween: [ "transform", "#Cow", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 8544, duration: 474, easing: "linear" },
            { id: "eid574", tween: [ "transform", "#Cow", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 9018, duration: 474, easing: "linear" },
            { id: "eid575", tween: [ "transform", "#Cow", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 9493, duration: 474, easing: "linear" },
            { id: "eid576", tween: [ "transform", "#Cow", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 9968, duration: 474, easing: "linear" },
            { id: "eid577", tween: [ "transform", "#Cow", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 10442, duration: 474, easing: "linear" },
            { id: "eid578", tween: [ "transform", "#Cow", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 10917, duration: 474, easing: "linear" },
            { id: "eid579", tween: [ "transform", "#Cow", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 11392, duration: 474, easing: "linear" },
            { id: "eid580", tween: [ "transform", "#Cow", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 11866, duration: 474, easing: "linear" },
            { id: "eid581", tween: [ "transform", "#Cow", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 12341, duration: 474, easing: "linear" },
            { id: "eid582", tween: [ "transform", "#Cow", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 12816, duration: 474, easing: "linear" },
            { id: "eid583", tween: [ "transform", "#Cow", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 13290, duration: 474, easing: "linear" },
            { id: "eid586", tween: [ "transform", "#Cow", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 13765, duration: 474, easing: "linear" },
            { id: "eid587", tween: [ "transform", "#Cow", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 14240, duration: 474, easing: "linear" },
            { id: "eid584", tween: [ "transform", "#Cow", "rotateZ", '0deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 14736, duration: 339, easing: "linear" },
            { id: "eid172", tween: [ "transform", "#zebra", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 0, duration: 500, easing: "linear" },
            { id: "eid286", tween: [ "transform", "#zebra", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 500, duration: 500, easing: "linear" },
            { id: "eid287", tween: [ "transform", "#zebra", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 1000, duration: 500, easing: "linear" },
            { id: "eid288", tween: [ "transform", "#zebra", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 1500, duration: 500, easing: "linear" },
            { id: "eid289", tween: [ "transform", "#zebra", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 2000, duration: 500, easing: "linear" },
            { id: "eid290", tween: [ "transform", "#zebra", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 2500, duration: 500, easing: "linear" },
            { id: "eid291", tween: [ "transform", "#zebra", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 3000, duration: 500, easing: "linear" },
            { id: "eid292", tween: [ "transform", "#zebra", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 3500, duration: 500, easing: "linear" },
            { id: "eid293", tween: [ "transform", "#zebra", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 4000, duration: 500, easing: "linear" },
            { id: "eid294", tween: [ "transform", "#zebra", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 4500, duration: 500, easing: "linear" },
            { id: "eid295", tween: [ "transform", "#zebra", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 5000, duration: 500, easing: "linear" },
            { id: "eid296", tween: [ "transform", "#zebra", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 5500, duration: 500, easing: "linear" },
            { id: "eid297", tween: [ "transform", "#zebra", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 6000, duration: 500, easing: "linear" },
            { id: "eid298", tween: [ "transform", "#zebra", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 6500, duration: 500, easing: "linear" },
            { id: "eid299", tween: [ "transform", "#zebra", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 7000, duration: 500, easing: "linear" },
            { id: "eid300", tween: [ "transform", "#zebra", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 7500, duration: 500, easing: "linear" },
            { id: "eid301", tween: [ "transform", "#zebra", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 8000, duration: 500, easing: "linear" },
            { id: "eid302", tween: [ "transform", "#zebra", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 8500, duration: 500, easing: "linear" },
            { id: "eid303", tween: [ "transform", "#zebra", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 9000, duration: 500, easing: "linear" },
            { id: "eid304", tween: [ "transform", "#zebra", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 9500, duration: 500, easing: "linear" },
            { id: "eid305", tween: [ "transform", "#zebra", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 10000, duration: 500, easing: "linear" },
            { id: "eid306", tween: [ "transform", "#zebra", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 10500, duration: 500, easing: "linear" },
            { id: "eid307", tween: [ "transform", "#zebra", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 11000, duration: 500, easing: "linear" },
            { id: "eid308", tween: [ "transform", "#zebra", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 11500, duration: 500, easing: "linear" },
            { id: "eid309", tween: [ "transform", "#zebra", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 12000, duration: 500, easing: "linear" },
            { id: "eid310", tween: [ "transform", "#zebra", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 12500, duration: 500, easing: "linear" },
            { id: "eid311", tween: [ "transform", "#zebra", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 13000, duration: 500, easing: "linear" },
            { id: "eid312", tween: [ "transform", "#zebra", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 13500, duration: 500, easing: "linear" },
            { id: "eid313", tween: [ "transform", "#zebra", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 14000, duration: 500, easing: "linear" },
            { id: "eid314", tween: [ "transform", "#zebra", "rotateZ", '0deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 14500, duration: 500, easing: "linear" },
            { id: "eid40", tween: [ "style", "#goat", "width", '98px', { valueTemplate: undefined, fromValue: '98px'}], position: 0, duration: 0, easing: "linear" },
            { id: "eid111", tween: [ "style", "#goat", "width", '98px', { valueTemplate: undefined, fromValue: '98px'}], position: 3000, duration: 0, easing: "linear" },
            { id: "eid104", tween: [ "transform", "#zebra", "translateY", '94.66666px', { valueTemplate: undefined, fromValue: '95px'}], position: 0, duration: 250, easing: "linear" },
            { id: "eid166", tween: [ "transform", "#zebra", "translateY", '93.99999px', { valueTemplate: undefined, fromValue: '94.66666px'}], position: 250, duration: 500, easing: "linear" },
            { id: "eid171", tween: [ "transform", "#zebra", "translateY", '93.66665px', { valueTemplate: undefined, fromValue: '93.99999px'}], position: 750, duration: 250, easing: "linear" },
            { id: "eid285", tween: [ "transform", "#zebra", "translateY", '91px', { valueTemplate: undefined, fromValue: '93.66665px'}], position: 1000, duration: 2000, easing: "linear" },
            { id: "eid120", tween: [ "transform", "#zebra", "translateY", '92px', { valueTemplate: undefined, fromValue: '91px'}], position: 3000, duration: 1000, easing: "linear" },
            { id: "eid134", tween: [ "transform", "#zebra", "translateY", '93px', { valueTemplate: undefined, fromValue: '92px'}], position: 4000, duration: 1000, easing: "linear" },
            { id: "eid148", tween: [ "transform", "#zebra", "translateY", '90px', { valueTemplate: undefined, fromValue: '93px'}], position: 5000, duration: 5000, easing: "linear" },
            { id: "eid98", tween: [ "transform", "#goat", "translateY", '69.666666666667px', { valueTemplate: undefined, fromValue: '70px'}], position: 0, duration: 250, easing: "linear" },
            { id: "eid169", tween: [ "transform", "#goat", "translateY", '66px', { valueTemplate: undefined, fromValue: '69.666666666667px'}], position: 250, duration: 2750, easing: "linear" },
            { id: "eid114", tween: [ "transform", "#goat", "translateY", '67px', { valueTemplate: undefined, fromValue: '66px'}], position: 3000, duration: 1000, easing: "linear" },
            { id: "eid128", tween: [ "transform", "#goat", "translateY", '68px', { valueTemplate: undefined, fromValue: '67px'}], position: 4000, duration: 1000, easing: "linear" },
            { id: "eid142", tween: [ "transform", "#goat", "translateY", '65px', { valueTemplate: undefined, fromValue: '68px'}], position: 5000, duration: 5000, easing: "linear" },
            { id: "eid525", tween: [ "transform", "#Giraffee", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 0, duration: 482, easing: "linear" },
            { id: "eid526", tween: [ "transform", "#Giraffee", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 482, duration: 482, easing: "linear" },
            { id: "eid527", tween: [ "transform", "#Giraffee", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 964, duration: 482, easing: "linear" },
            { id: "eid528", tween: [ "transform", "#Giraffee", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 1446, duration: 482, easing: "linear" },
            { id: "eid529", tween: [ "transform", "#Giraffee", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 1929, duration: 482, easing: "linear" },
            { id: "eid530", tween: [ "transform", "#Giraffee", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 2411, duration: 482, easing: "linear" },
            { id: "eid531", tween: [ "transform", "#Giraffee", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 2893, duration: 482, easing: "linear" },
            { id: "eid532", tween: [ "transform", "#Giraffee", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 3376, duration: 482, easing: "linear" },
            { id: "eid533", tween: [ "transform", "#Giraffee", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 3858, duration: 482, easing: "linear" },
            { id: "eid534", tween: [ "transform", "#Giraffee", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 4340, duration: 482, easing: "linear" },
            { id: "eid535", tween: [ "transform", "#Giraffee", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 4823, duration: 482, easing: "linear" },
            { id: "eid536", tween: [ "transform", "#Giraffee", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 5305, duration: 482, easing: "linear" },
            { id: "eid537", tween: [ "transform", "#Giraffee", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 5787, duration: 482, easing: "linear" },
            { id: "eid538", tween: [ "transform", "#Giraffee", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 6270, duration: 482, easing: "linear" },
            { id: "eid539", tween: [ "transform", "#Giraffee", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 6752, duration: 482, easing: "linear" },
            { id: "eid540", tween: [ "transform", "#Giraffee", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 7234, duration: 482, easing: "linear" },
            { id: "eid541", tween: [ "transform", "#Giraffee", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 7717, duration: 482, easing: "linear" },
            { id: "eid542", tween: [ "transform", "#Giraffee", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 8199, duration: 482, easing: "linear" },
            { id: "eid543", tween: [ "transform", "#Giraffee", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 8681, duration: 482, easing: "linear" },
            { id: "eid544", tween: [ "transform", "#Giraffee", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 9163, duration: 482, easing: "linear" },
            { id: "eid545", tween: [ "transform", "#Giraffee", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 9646, duration: 482, easing: "linear" },
            { id: "eid546", tween: [ "transform", "#Giraffee", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 10128, duration: 482, easing: "linear" },
            { id: "eid547", tween: [ "transform", "#Giraffee", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 10610, duration: 482, easing: "linear" },
            { id: "eid548", tween: [ "transform", "#Giraffee", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 11093, duration: 482, easing: "linear" },
            { id: "eid549", tween: [ "transform", "#Giraffee", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 11575, duration: 482, easing: "linear" },
            { id: "eid550", tween: [ "transform", "#Giraffee", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 12057, duration: 482, easing: "linear" },
            { id: "eid551", tween: [ "transform", "#Giraffee", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 12540, duration: 482, easing: "linear" },
            { id: "eid552", tween: [ "transform", "#Giraffee", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 13022, duration: 482, easing: "linear" },
            { id: "eid553", tween: [ "transform", "#Giraffee", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 13504, duration: 482, easing: "linear" },
            { id: "eid588", tween: [ "transform", "#Giraffee", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 13987, duration: 482, easing: "linear" },
            { id: "eid554", tween: [ "transform", "#Giraffee", "rotateZ", '0deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 14469, duration: 606, easing: "linear" },
            { id: "eid66", tween: [ "style", "#Hippo", "width", '96px', { valueTemplate: undefined, fromValue: '96px'}], position: 0, duration: 0, easing: "linear" },
            { id: "eid99", tween: [ "transform", "#Giraffee", "translateX", '-458px', { valueTemplate: undefined, fromValue: '-693px'}], position: 0, duration: 3000, easing: "linear" },
            { id: "eid115", tween: [ "transform", "#Giraffee", "translateX", '-387px', { valueTemplate: undefined, fromValue: '-458px'}], position: 3000, duration: 1000, easing: "linear" },
            { id: "eid129", tween: [ "transform", "#Giraffee", "translateX", '-312px', { valueTemplate: undefined, fromValue: '-387px'}], position: 4000, duration: 1000, easing: "linear" },
            { id: "eid143", tween: [ "transform", "#Giraffee", "translateX", '-43px', { valueTemplate: undefined, fromValue: '-312px'}], position: 5000, duration: 5000, easing: "linear" },
            { id: "eid156", tween: [ "transform", "#Giraffee", "translateX", '126px', { valueTemplate: undefined, fromValue: '-43px'}], position: 10000, duration: 5000, easing: "linear" },
            { id: "eid110", tween: [ "transform", "#Hippo", "translateY", '84px', { valueTemplate: undefined, fromValue: '88px'}], position: 0, duration: 3000, easing: "linear" },
            { id: "eid126", tween: [ "transform", "#Hippo", "translateY", '85px', { valueTemplate: undefined, fromValue: '84px'}], position: 3000, duration: 1000, easing: "linear" },
            { id: "eid140", tween: [ "transform", "#Hippo", "translateY", '86px', { valueTemplate: undefined, fromValue: '85px'}], position: 4000, duration: 1000, easing: "linear" },
            { id: "eid154", tween: [ "transform", "#Hippo", "translateY", '83px', { valueTemplate: undefined, fromValue: '86px'}], position: 5000, duration: 5000, easing: "linear" },
            { id: "eid108", tween: [ "transform", "#Cow", "translateY", '80px', { valueTemplate: undefined, fromValue: '84px'}], position: 0, duration: 3000, easing: "linear" },
            { id: "eid124", tween: [ "transform", "#Cow", "translateY", '81px', { valueTemplate: undefined, fromValue: '80px'}], position: 3000, duration: 1000, easing: "linear" },
            { id: "eid138", tween: [ "transform", "#Cow", "translateY", '82px', { valueTemplate: undefined, fromValue: '81px'}], position: 4000, duration: 1000, easing: "linear" },
            { id: "eid152", tween: [ "transform", "#Cow", "translateY", '79px', { valueTemplate: undefined, fromValue: '82px'}], position: 5000, duration: 5000, easing: "linear" },
            { id: "eid34", tween: [ "style", "#Giraffee", "width", '68px', { valueTemplate: undefined, fromValue: '68px'}], position: 0, duration: 0, easing: "linear" },
            { id: "eid345", tween: [ "transform", "#owl", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 0, duration: 491, easing: "linear" },
            { id: "eid346", tween: [ "transform", "#owl", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 491, duration: 491, easing: "linear" },
            { id: "eid347", tween: [ "transform", "#owl", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 983, duration: 491, easing: "linear" },
            { id: "eid348", tween: [ "transform", "#owl", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 1475, duration: 491, easing: "linear" },
            { id: "eid349", tween: [ "transform", "#owl", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 1966, duration: 491, easing: "linear" },
            { id: "eid350", tween: [ "transform", "#owl", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 2458, duration: 491, easing: "linear" },
            { id: "eid351", tween: [ "transform", "#owl", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 2950, duration: 491, easing: "linear" },
            { id: "eid352", tween: [ "transform", "#owl", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 3441, duration: 491, easing: "linear" },
            { id: "eid353", tween: [ "transform", "#owl", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 3933, duration: 491, easing: "linear" },
            { id: "eid354", tween: [ "transform", "#owl", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 4425, duration: 491, easing: "linear" },
            { id: "eid355", tween: [ "transform", "#owl", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 4916, duration: 491, easing: "linear" },
            { id: "eid356", tween: [ "transform", "#owl", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 5408, duration: 491, easing: "linear" },
            { id: "eid357", tween: [ "transform", "#owl", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 5900, duration: 491, easing: "linear" },
            { id: "eid358", tween: [ "transform", "#owl", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 6391, duration: 491, easing: "linear" },
            { id: "eid359", tween: [ "transform", "#owl", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 6883, duration: 491, easing: "linear" },
            { id: "eid360", tween: [ "transform", "#owl", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 7375, duration: 491, easing: "linear" },
            { id: "eid361", tween: [ "transform", "#owl", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 7866, duration: 491, easing: "linear" },
            { id: "eid362", tween: [ "transform", "#owl", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 8358, duration: 491, easing: "linear" },
            { id: "eid363", tween: [ "transform", "#owl", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 8850, duration: 491, easing: "linear" },
            { id: "eid364", tween: [ "transform", "#owl", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 9341, duration: 491, easing: "linear" },
            { id: "eid365", tween: [ "transform", "#owl", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 9833, duration: 491, easing: "linear" },
            { id: "eid366", tween: [ "transform", "#owl", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 10325, duration: 491, easing: "linear" },
            { id: "eid367", tween: [ "transform", "#owl", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 10816, duration: 491, easing: "linear" },
            { id: "eid368", tween: [ "transform", "#owl", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 11308, duration: 491, easing: "linear" },
            { id: "eid369", tween: [ "transform", "#owl", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 11800, duration: 491, easing: "linear" },
            { id: "eid370", tween: [ "transform", "#owl", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 12291, duration: 491, easing: "linear" },
            { id: "eid371", tween: [ "transform", "#owl", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 12783, duration: 491, easing: "linear" },
            { id: "eid372", tween: [ "transform", "#owl", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 13275, duration: 491, easing: "linear" },
            { id: "eid373", tween: [ "transform", "#owl", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 13766, duration: 491, easing: "linear" },
            { id: "eid374", tween: [ "transform", "#owl", "rotateZ", '0deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 14258, duration: 741, easing: "linear" },
            { id: "eid105", tween: [ "transform", "#owl", "translateX", '7px', { valueTemplate: undefined, fromValue: '-228px'}], position: 0, duration: 3000, easing: "linear" },
            { id: "eid121", tween: [ "transform", "#owl", "translateX", '78px', { valueTemplate: undefined, fromValue: '7px'}], position: 3000, duration: 1000, easing: "linear" },
            { id: "eid135", tween: [ "transform", "#owl", "translateX", '153px', { valueTemplate: undefined, fromValue: '78px'}], position: 4000, duration: 1000, easing: "linear" },
            { id: "eid149", tween: [ "transform", "#owl", "translateX", '422px', { valueTemplate: undefined, fromValue: '153px'}], position: 5000, duration: 5000, easing: "linear" },
            { id: "eid159", tween: [ "transform", "#owl", "translateX", '591px', { valueTemplate: undefined, fromValue: '422px'}], position: 10000, duration: 5000, easing: "linear" },
            { id: "eid103", tween: [ "transform", "#zebra", "translateX", '-64.41667px', { valueTemplate: undefined, fromValue: '-84px'}], position: 0, duration: 250, easing: "linear" },
            { id: "eid165", tween: [ "transform", "#zebra", "translateX", '-25.25001px', { valueTemplate: undefined, fromValue: '-64.41667px'}], position: 250, duration: 500, easing: "linear" },
            { id: "eid170", tween: [ "transform", "#zebra", "translateX", '-5.66668px', { valueTemplate: undefined, fromValue: '-25.25001px'}], position: 750, duration: 250, easing: "linear" },
            { id: "eid284", tween: [ "transform", "#zebra", "translateX", '151px', { valueTemplate: undefined, fromValue: '-5.66668px'}], position: 1000, duration: 2000, easing: "linear" },
            { id: "eid119", tween: [ "transform", "#zebra", "translateX", '222px', { valueTemplate: undefined, fromValue: '151px'}], position: 3000, duration: 1000, easing: "linear" },
            { id: "eid133", tween: [ "transform", "#zebra", "translateX", '297px', { valueTemplate: undefined, fromValue: '222px'}], position: 4000, duration: 1000, easing: "linear" },
            { id: "eid147", tween: [ "transform", "#zebra", "translateX", '566px', { valueTemplate: undefined, fromValue: '297px'}], position: 5000, duration: 5000, easing: "linear" },
            { id: "eid158", tween: [ "transform", "#zebra", "translateX", '739px', { valueTemplate: undefined, fromValue: '566px'}], position: 10000, duration: 5000, easing: "linear" },
            { id: "eid100", tween: [ "transform", "#Giraffee", "translateY", '69px', { valueTemplate: undefined, fromValue: '73px'}], position: 0, duration: 3000, easing: "linear" },
            { id: "eid116", tween: [ "transform", "#Giraffee", "translateY", '70px', { valueTemplate: undefined, fromValue: '69px'}], position: 3000, duration: 1000, easing: "linear" },
            { id: "eid130", tween: [ "transform", "#Giraffee", "translateY", '71px', { valueTemplate: undefined, fromValue: '70px'}], position: 4000, duration: 1000, easing: "linear" },
            { id: "eid144", tween: [ "transform", "#Giraffee", "translateY", '68px', { valueTemplate: undefined, fromValue: '71px'}], position: 5000, duration: 5000, easing: "linear" },
            { id: "eid495", tween: [ "transform", "#Hippo", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 0, duration: 491, easing: "linear" },
            { id: "eid496", tween: [ "transform", "#Hippo", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 491, duration: 491, easing: "linear" },
            { id: "eid497", tween: [ "transform", "#Hippo", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 983, duration: 491, easing: "linear" },
            { id: "eid498", tween: [ "transform", "#Hippo", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 1475, duration: 491, easing: "linear" },
            { id: "eid499", tween: [ "transform", "#Hippo", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 1966, duration: 491, easing: "linear" },
            { id: "eid500", tween: [ "transform", "#Hippo", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 2458, duration: 491, easing: "linear" },
            { id: "eid501", tween: [ "transform", "#Hippo", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 2950, duration: 491, easing: "linear" },
            { id: "eid502", tween: [ "transform", "#Hippo", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 3441, duration: 491, easing: "linear" },
            { id: "eid503", tween: [ "transform", "#Hippo", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 3933, duration: 491, easing: "linear" },
            { id: "eid504", tween: [ "transform", "#Hippo", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 4425, duration: 491, easing: "linear" },
            { id: "eid505", tween: [ "transform", "#Hippo", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 4916, duration: 491, easing: "linear" },
            { id: "eid506", tween: [ "transform", "#Hippo", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 5408, duration: 491, easing: "linear" },
            { id: "eid507", tween: [ "transform", "#Hippo", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 5900, duration: 491, easing: "linear" },
            { id: "eid508", tween: [ "transform", "#Hippo", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 6391, duration: 491, easing: "linear" },
            { id: "eid509", tween: [ "transform", "#Hippo", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 6883, duration: 491, easing: "linear" },
            { id: "eid510", tween: [ "transform", "#Hippo", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 7375, duration: 491, easing: "linear" },
            { id: "eid511", tween: [ "transform", "#Hippo", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 7866, duration: 491, easing: "linear" },
            { id: "eid512", tween: [ "transform", "#Hippo", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 8358, duration: 491, easing: "linear" },
            { id: "eid513", tween: [ "transform", "#Hippo", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 8850, duration: 491, easing: "linear" },
            { id: "eid514", tween: [ "transform", "#Hippo", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 9341, duration: 491, easing: "linear" },
            { id: "eid515", tween: [ "transform", "#Hippo", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 9833, duration: 491, easing: "linear" },
            { id: "eid516", tween: [ "transform", "#Hippo", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 10325, duration: 491, easing: "linear" },
            { id: "eid517", tween: [ "transform", "#Hippo", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 10816, duration: 491, easing: "linear" },
            { id: "eid518", tween: [ "transform", "#Hippo", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 11308, duration: 491, easing: "linear" },
            { id: "eid519", tween: [ "transform", "#Hippo", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 11800, duration: 491, easing: "linear" },
            { id: "eid520", tween: [ "transform", "#Hippo", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 12291, duration: 491, easing: "linear" },
            { id: "eid521", tween: [ "transform", "#Hippo", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 12783, duration: 491, easing: "linear" },
            { id: "eid522", tween: [ "transform", "#Hippo", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 13275, duration: 491, easing: "linear" },
            { id: "eid523", tween: [ "transform", "#Hippo", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 13766, duration: 491, easing: "linear" },
            { id: "eid524", tween: [ "transform", "#Hippo", "rotateZ", '0deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 14258, duration: 741, easing: "linear" },
            { id: "eid465", tween: [ "transform", "#pig", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 0, duration: 480, easing: "linear" },
            { id: "eid466", tween: [ "transform", "#pig", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 480, duration: 480, easing: "linear" },
            { id: "eid467", tween: [ "transform", "#pig", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 960, duration: 480, easing: "linear" },
            { id: "eid468", tween: [ "transform", "#pig", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 1440, duration: 480, easing: "linear" },
            { id: "eid469", tween: [ "transform", "#pig", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 1920, duration: 480, easing: "linear" },
            { id: "eid470", tween: [ "transform", "#pig", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 2400, duration: 480, easing: "linear" },
            { id: "eid471", tween: [ "transform", "#pig", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 2880, duration: 480, easing: "linear" },
            { id: "eid472", tween: [ "transform", "#pig", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 3360, duration: 480, easing: "linear" },
            { id: "eid473", tween: [ "transform", "#pig", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 3840, duration: 480, easing: "linear" },
            { id: "eid474", tween: [ "transform", "#pig", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 4320, duration: 480, easing: "linear" },
            { id: "eid475", tween: [ "transform", "#pig", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 4800, duration: 480, easing: "linear" },
            { id: "eid476", tween: [ "transform", "#pig", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 5280, duration: 480, easing: "linear" },
            { id: "eid477", tween: [ "transform", "#pig", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 5760, duration: 480, easing: "linear" },
            { id: "eid478", tween: [ "transform", "#pig", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 6240, duration: 480, easing: "linear" },
            { id: "eid479", tween: [ "transform", "#pig", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 6720, duration: 480, easing: "linear" },
            { id: "eid480", tween: [ "transform", "#pig", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 7200, duration: 480, easing: "linear" },
            { id: "eid481", tween: [ "transform", "#pig", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 7680, duration: 480, easing: "linear" },
            { id: "eid482", tween: [ "transform", "#pig", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 8160, duration: 480, easing: "linear" },
            { id: "eid483", tween: [ "transform", "#pig", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 8640, duration: 480, easing: "linear" },
            { id: "eid484", tween: [ "transform", "#pig", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 9120, duration: 480, easing: "linear" },
            { id: "eid485", tween: [ "transform", "#pig", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 9600, duration: 480, easing: "linear" },
            { id: "eid486", tween: [ "transform", "#pig", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 10081, duration: 480, easing: "linear" },
            { id: "eid487", tween: [ "transform", "#pig", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 10561, duration: 480, easing: "linear" },
            { id: "eid488", tween: [ "transform", "#pig", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 11041, duration: 480, easing: "linear" },
            { id: "eid489", tween: [ "transform", "#pig", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 11521, duration: 480, easing: "linear" },
            { id: "eid490", tween: [ "transform", "#pig", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 12001, duration: 480, easing: "linear" },
            { id: "eid491", tween: [ "transform", "#pig", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 12481, duration: 480, easing: "linear" },
            { id: "eid492", tween: [ "transform", "#pig", "rotateZ", '-5deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 12961, duration: 480, easing: "linear" },
            { id: "eid493", tween: [ "transform", "#pig", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 13441, duration: 514, easing: "linear" },
            { id: "eid589", tween: [ "transform", "#pig", "rotateZ", '5deg', { valueTemplate: undefined, fromValue: '-5deg'}], position: 13955, duration: 514, easing: "linear" },
            { id: "eid494", tween: [ "transform", "#pig", "rotateZ", '0deg', { valueTemplate: undefined, fromValue: '5deg'}], position: 14469, duration: 530, easing: "linear" }]
      }
   },
}};


$(window).ready(function() {
     $.Edge.initialize(symbols);
});

$(window).load(function() {
    $.Edge.play();
});
